apiVersion: v1
kind: Service
metadata:
  name: cart-services
  namespace: choosemood
  labels:
    app: cart-services
    service: backend
spec:
  selector:
    app: cart-services
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
  type: ClusterIP
